# Generated by Django 2.1.7 on 2019-03-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("froide_crowdfunding", "0003_contribution_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
