# Generated by Django 2.1.8 on 2019-04-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_crowdfunding', '0004_contribution_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfunding',
            name='public_interest',
            field=models.TextField(blank=True),
        ),
    ]
