# Generated by Django 2.2.4 on 2019-09-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("froide_crowdfunding", "0006_auto_20190513_1125"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crowdfunding",
            options={
                "get_latest_by": "date_requested",
                "ordering": ("-date_requested",),
                "permissions": (("can_crowdfund", "Can use crowdfunding"),),
                "verbose_name": "Crowdfunding",
                "verbose_name_plural": "Crowdfundings",
            },
        ),
    ]
