# Generated by Django 2.2.4 on 2019-10-08 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('froide_crowdfunding', '0009_crowdfundingformcmsplugin_crowdfundingprogresscmsplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdfundingContributorsCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='froide_crowdfunding_crowdfundingcontributorscmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('crowdfunding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='froide_crowdfunding.Crowdfunding')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
