# Generated by Django 3.0.8 on 2020-11-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("froide_crowdfunding", "0010_crowdfundingcontributorscmsplugin"),
    ]

    operations = [
        migrations.AddField(
            model_name="crowdfunding",
            name="show_in_list",
            field=models.BooleanField(default=True),
        )
    ]
